### PR TITLE
Integrate WinProxySelector

### PR DESCRIPTION
**Pull request by akuhtz**

### CODE REVIEW

**Comment by dragetd** [comment]
Is this a WIP? Or do you need feedback? What is the state of the PR?

**Comment by akuhtz** [comment]
@dragetd  I found this change in a fork but didn't had time to integrate it. Feedback is welcome.

**Comment by akuhtz** [comment]
Was integrated with PR #17

**Comment by dragetd** [comment]
Ahh…
I was going to review the code. I saw the 'Closed' and thought you merged it.

But it was removing the rhino JS engine and changing a bunch of things, where I thought 'Hmm, this is confusing. Aren't these changes already in this fork? Wasn't this one of the reason why I choose it back then?

It took me way to long to realize that this PR was closed by 'not mergeing' it. xD

**Comment by akuhtz** [comment]
@dragetd I had to add more changes and the PR was created from a fork and I didn't had it locally. The only solution for me was to checkout this PR and provide a new PR #17 based on my checkout. You can have a look at #17 that was merged yesterday and is released already as 1.0.11.
If you see some issue please report back.

**Pull request closed without merging**
